title: date | tail -f
url: "https://baobaoyeye.github.io"
baseurl: ""

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://baobaoyeye.github.io"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Index"
   link: "/"
 - name: "About"
   link: "/about"
